server:
  port: 7073
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 12345
#  cloud:
#    zookeeper:
#      connect-string: 192.168.43.76:2181
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fdd.springcloud.entities
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/